version: "3.8"
services:
  server:
    build:
      context: ../../
      dockerfile: RealTest/docker/server/Dockerfile
    ports:
      - "80:80"

  client:
    build:
      context: ../../
      dockerfile: RealTest/docker/client/Dockerfile