version: "3.8"
services:
  server:
    build:
      context: ../../
      dockerfile: RealTest/docker/server/Dockerfile

  client:
    build:
      context: ../../
      dockerfile: RealTest/docker/client/Dockerfile