name: build-and-publish

on:
  push:
    tags:        
      - '*'

jobs:
  build:
    name: build-test-package
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore --packages packages
    - name: Build
      run: dotnet build --configuration Release --no-restore BSU
    #- name: Test
      #run: dotnet test
    - name: Publish
      run: dotnet publish -c Release -o publish BSU
    - name: Package
      run: nuget pack -OutputFileNamesWithoutVersion -Version ${{ github.refname }}
      # TODO: download former releases
    - name: Releasify
      run: powershell.exe -ExecutionPolicy Bypass -Command "packages\squirrel.windows\1.9.0\tools\Squirrel.exe -r releases --releasify  BSU.nupkg ... | Write-Output"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: releases
        path: releases/*


  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: BeowulfStratOps/BSU-releases
    - name: Get build artifacts
      uses: actions/download-artifact@v2
      with:
        name: releases
        path: files

